### PR TITLE
Fix issue #18

### PR DESCRIPTION
**Pull request by axelmierczuk**

### CODE REVIEW

**Comment by ColdHeat** [comment]
@n132 are you able to give out permission for this repo?

**Comment by n132** [comment]
Thanks, @ColdHeat, and sorry for the late reply @axelmierczuk. I am not able to change the permission for this repo and I just asked @Racheltrq to help us with that.

**Comment by Racheltrq** [comment]
@axelmierczuk Hi, I've added you back to the repo :] Sorry for the inconvenience.

**Comment by axelmierczuk** [comment]
Thanks everyone!

**Pull request merged**
