### PR TITLE
IDA 7.x / Python3 Compatibility

### PR DESCRIPTION
**Pull request by axelmierczuk**
I have updated this plugin to work with IDA 7.x and Python3. Next step would be to add backwards compatibility to Python2 or mark as deprecated.

### CODE REVIEW

**Comment by ColdHeat** [comment]
Hello I believe you requested access to the PySide exe stored in my Google Drive. I don't remember why this wasn't put into the Github in the first place but we could probably do that if it's still needed.

**Comment by axelmierczuk** [comment]
Yes I did. I decided to work on the project instead and update it to IDA 7.x and Python3. If backwards compatibility is required for this PR then I can add it, but Python2 and IDA 6.x is deprecated so I don't see why it would be required.

**Comment by ColdHeat** [comment]
Okay cool, I uploaded them into the repo anyway to get them out of my Google Drive. If there's no need for them anymore you can always delete them. 

I won't be reviewing any PRs for the project since it's been quite some time and I don't have any use for the project now. Feel free to take over and merge freely.

**Comment by axelmierczuk** [comment]
Awesome, thanks. Could you grant me write access?

**Comment by ColdHeat** [comment]
I don't think I have the ability to change that, you'll probalby need to ask someone else. I can merge the PR for you though.

**Pull request merged**
